### ISSUE TITLE
geckodriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by Aju100** [askbuddie/ABMails#9]
Hello ,when I use python3 abmails.py -- receive commands, it got this problems. Yeah, i know that i must install geckko driver, but i was not able to . Any guide to install gecko driver. I looked through the documentation too.
![geek](https://user-images.githubusercontent.com/29862610/60441142-18d09280-9c36-11e9-9298-67b4b1c0f587.png)

**Comment by prdp1137** [comment]
@Aju100, I guess you haven't gone through README.MD, it's clearly documented. You need to the zip file of gecko driver and further extract it, and copy the extracted file in /usr/bin or /usr/local/bin depending upon your distro. Meanwhile, don't forget to make it  executable using `chmod +x geckodriver` 

![image](https://user-images.githubusercontent.com/29733866/60443142-4fa8a780-9c3a-11e9-98f9-56e97f4d5309.png)

**Comment by Aju100** [comment]
i have done same instructions. it doesn't but now it had been solved @pr0d33p  .

**Comment by prdp1137** [comment]
@Aju100 would you mind closing this issue as this has been solved!
